export const IMAGE_CATEGORIES = [
  'Front Exterior',
  'Rear Exterior',
  'Driver Side',
  'Passenger Side',
  'Interior (Front)',
  'Interior (Rear)',
  'Tires & Wheels',
  'Engine Bay',
  'Undercarriage',
  'Dashboard/VIN',
  'Odometer',
  'Damage/Misc',
];

// Vehicle-type-specific image categories for specialized inspections
export const VEHICLE_TYPE_IMAGE_CATEGORIES: Record<string, string[]> = {
  Standard: IMAGE_CATEGORIES,
  EV: [
    'Front Exterior',
    'Rear Exterior',
    'Driver Side',
    'Passenger Side',
    'Interior (Front)',
    'Interior (Rear)',
    'Tires & Wheels',
    'Charge Port',
    'Undercarriage',
    'Dashboard/VIN',
    'Odometer',
    'Frunk/Trunk',
    'Damage/Misc',
  ],
  Commercial: [
    'Cab Front',
    'Cab Rear',
    'Cab Driver Side',
    'Cab Passenger Side',
    'Cab Interior',
    'Dashboard/Gauges',
    'DOT Stickers/Plates',
    'Frame Rails',
    'Steer Tires',
    'Drive Tires (Inner/Outer)',
    'Trailer Tires',
    'Fifth Wheel/Coupling',
    'Air Brake Components',
    'Exhaust System',
    'Liftgate/Hydraulics',
    'Reflective Tape & Lights',
    'Undercarriage',
    'Damage/Misc',
  ],
  RV: [
    'Coach Front',
    'Coach Rear',
    'Coach Driver Side',
    'Coach Passenger Side',
    'Roof Condition',
    'Awnings & Slide-Outs',
    'Interior Living Area',
    'Kitchen/Appliances',
    'Bathroom',
    'Bedroom',
    'Dashboard/Cockpit',
    'Propane System',
    'Water Hookups',
    'Electrical Panel',
    'Storage Compartments',
    'Undercarriage/Frame',
    'Tires & Wheels',
    'Damage/Water Intrusion',
  ],
  Classic: [
    'Front 3/4 View',
    'Rear 3/4 View',
    'Driver Side Profile',
    'Passenger Side Profile',
    'Engine Bay',
    'Trunk',
    'Interior (Front)',
    'Interior (Rear)',
    'Dashboard/Gauges',
    'Undercarriage',
    'Frame/Floor Pans',
    'VIN Plate/Data Tag',
    'Paint Close-Up',
    'Chrome/Trim Details',
    'Numbers Matching (Engine/Trans)',
    'Documentation/Records',
    'Damage/Rust/Bondo',
  ],
  Motorcycle: [
    'Front View',
    'Rear View',
    'Left Side Profile',
    'Right Side Profile',
    'Engine Close-Up',
    'Exhaust System',
    'Front Wheel/Forks',
    'Rear Wheel/Swingarm',
    'Dashboard/Gauges',
    'Controls (Handlebars)',
    'Chain/Belt/Shaft',
    'Frame/VIN',
    'Damage/Misc',
  ],
};

// Comprehensive, categorized checklists for different vehicle types
export const VEHICLE_INSPECTION_TEMPLATES = {
  Standard: {
    'Exterior & Body': ['Body Panels for Dents/Scratches', 'Glass & Mirrors Condition', 'Lights & Lenses Function', 'Frame/Unibody Integrity', 'Wiper Blade Condition'],
    'Tires & Brakes': ['Tire Tread Depth & Condition (All 4 + Spare)', 'Brake Pad Life (Visual)', 'Rotors/Drums Condition', 'Brake Fluid Level & Color', 'Emergency Brake Function'],
    'Engine Compartment': ['Engine Oil Level & Condition', 'Coolant Level & Condition', 'Belts & Hoses Condition', 'Battery Terminals & Health', 'Visible Fluid Leaks', 'Engine Air Filter'],
    'Interior': ['Upholstery & Carpet Condition', 'Dashboard & Controls Function', 'HVAC System (Heat & A/C)', 'Audio & Infotainment System', 'Warning Lights on Dash', 'Odor Check'],
    'Test Drive': ['Engine Performance & Acceleration', 'Transmission Shifting Smoothness', 'Steering & Alignment', 'Suspension Noise & Performance', 'Braking Performance (Noises, Pulsation)'],
  },
  EV: {
    'Exterior & Body': ['Body Panels for Dents/Scratches', 'Glass & Mirrors Condition', 'LED Lights & Lenses Function', 'Frame/Unibody Integrity'],
    'Tires & Brakes': ['Tire Tread Depth & Condition', 'Brake Pad Life (Regen affects wear)', 'Brake Fluid Level & Color', 'Emergency Brake Function'],
    'Battery & Charging': ['State of Health (SoH) Reading', 'Charge Port Condition', 'Charging Cable Included & Condition', 'Onboard Charger Function', 'Thermal Management System (Visual)'],
    'Interior & Electronics': ['Upholstery & Carpet Condition', 'Main Display & Controls Function', 'HVAC System (Heat Pump/Resistive)', 'Driver Assist Systems (ADAS) Function', 'Warning Lights on Dash'],
    'Test Drive': ['Motor Performance & Acceleration', 'Regenerative Braking Function', 'Steering & Alignment', 'Suspension Noise & Performance', 'Unusual Electrical Noises'],
  },
  Commercial: {
    'Cab Exterior': ['Body Panels & Fairings', 'Windshield & Mirrors (No Cracks)', 'Lights & Reflective Tapes (DOT)', 'Entry Steps & Grab Handles'],
    'Chassis & Drivetrain': ['Frame Rails (No Cracks/Bends)', 'Visible Fluid Leaks (Engine, Trans, Axles)', 'Exhaust System Integrity', 'Driveshaft & U-Joints'],
    'Tires, Wheels & Brakes': ['Tire Tread Depth (>4/32" Steer, >2/32" Other)', 'Dual Tire Spacing & Condition', 'Hub Oil Levels', 'Air Brake System (Leaks, Hoses)', 'Brake Adjustment (Slack Adjusters)'],
    'Cab Interior': ['Gauges & Warning Lights', 'HVAC & Defroster', 'Safety Equipment (Horn, Wipers, Fire Ext.)', 'Hours & Odometer Reading'],
    'Special Equipment': ['Fifth Wheel & Locking Jaw', 'Hydraulic Systems (If applicable)', 'Liftgate Operation (If applicable)'],
  },
  RV: {
    'Coach Exterior': ['Roof Condition & Seals', 'Sidewalls (Delamination Check)', 'Awnings & Slide-Outs Operation', 'Windows & Seals', 'Storage Compartment Doors'],
    'Chassis (Motorhome) / Frame (Trailer)': ['Frame Condition (Rust, Cracks)', 'Tire Age & Condition (Sidewall Cracking)', 'Suspension Components (Springs, Airbags)', 'Leveling Jacks Operation'],
    'Life Support Systems': ['Propane System (Leak Check)', 'Freshwater System (Pump, Faucets)', 'Wastewater Tanks & Valves', 'House Battery Bank Health'],
    'Interior Appliances': ['Refrigerator Operation (Gas & Electric)', 'Stove & Oven Function', 'Water Heater Function', 'Furnace & AC Operation'],
    'Cabin': ['Signs of Water Intrusion (Stains)', 'Cabinetry & Flooring Condition', 'Furniture Upholstery', 'Safety Devices (Smoke, LP, CO Detectors)'],
  },
  Classic: {
    'Body & Paint': ['Paint Quality & Originality', 'Panel Gaps & Alignment', 'Chrome & Trim Condition', 'Evidence of Bondo/Fillers (Magnet Test)'],
    'Frame & Undercarriage': ['Frame Rails for Rust/Rot/Repairs', 'Floor Pans Integrity', 'Suspension Bushings & Components (Age)', 'Originality of Undercarriage'],
    'Engine & Drivetrain': ['Engine Numbers Matching (If applicable)', 'Carburetor/Fuel Injection Condition', 'Originality of Components', 'Exhaust System (Rust, Originality)'],
    'Interior': ['Upholstery Originality & Condition', 'Dashboard, Gauges & Radio Originality', 'Headliner & Carpet', 'Correctness of Switches & Knobs'],
    'Documentation': ['History & Service Records', 'Original Bill of Sale / Window Sticker', 'Restoration Photo Album', 'VIN & Title Verification'],
  },
  Motorcycle: {
    'Controls & Electrical': ['Handlebars, Levers, Switches', 'Lights & Signals Function', 'Battery Health & Terminals', 'Wiring Condition'],
    'Engine & Transmission': ['Visible Oil Leaks', 'Clutch Engagement & Feel', 'Exhaust System Condition', 'Engine Noises (Cold & Warm)'],
    'Frame, Wheels & Tires': ['Frame for Damage/Cracks', 'Tire Age & Tread', 'Wheel Rims & Spokes/Casting', 'Fork Seals (No Leaks)'],
    'Final Drive': ['Chain/Belt Tension & Condition', 'Sprocket/Pulley Wear', 'Shaft Drive Fluid (If applicable)'],
    'Brakes & Suspension': ['Brake Pad Life & Rotor Condition', 'Brake Fluid Level & Color', 'Front & Rear Suspension Action'],
  },
};

// DOT / FMCSA compliance checklist for commercial vehicles (18-wheelers)
export const COMMERCIAL_DOT_COMPLIANCE = {
  'FMCSA / DOT Compliance': [
    'Valid USDOT Number Displayed',
    'MC Authority Number (If applicable)',
    'IFTA Sticker Current',
    'Annual Vehicle Inspection Sticker Current',
    'Fire Extinguisher (Rated 5 B:C or greater, charged)',
    'Warning Triangles/Flares (3 required)',
    'Spare Fuses (If equipped)',
    'Tire Chains (Seasonal/Regional requirement)',
    'Coupling Devices Secured (Kingpin, Pintle, Drawbar)',
    'Mud Flaps/Splash Guards Present',
    'Hazmat Placards (If applicable)',
  ],
  'Air Brake System Test': [
    'Governor Cut-Out Pressure (120-145 PSI)',
    'Governor Cut-In Pressure (Within 20-25 PSI of cut-out)',
    'Low Air Warning Activates (Below 60 PSI)',
    'Parking Brake Holds at Full Application',
    'Service Brake Stopping Distance (Loaded/Empty)',
    'Air Loss Rate (Static: <2 PSI/min single, <3 PSI/min combo)',
    'Slack Adjuster Stroke Length (Within limits)',
    'Brake Drum/Rotor Condition (No cracks, within thickness)',
    'ABS Indicator Light Functional',
  ],
  'Lighting & Electrical (DOT)': [
    'All Required Marker Lights Operational',
    'Clearance Lights (Front, Side, Rear)',
    'Reflective Tape Condition (Red rear, White front, Alternating sides)',
    'Turn Signals (Tractor & Trailer)',
    'Brake Lights (Tractor & Trailer)',
    'Headlights (High & Low Beam)',
    'License Plate Light',
    'Trailer ABS Indicator (Exterior)',
  ],
};

// RV habitability & safety checklist
export const RV_HABITABILITY_CHECKLIST = {
  'LP Gas (Propane) Safety': [
    'LP Leak Test (Soapy water at all connections)',
    'Regulator Condition & Mounting',
    'LP Lines (No chafing, secure mounting)',
    'Automatic LP Shutoff Valve',
    'LP Detector Functional (Interior)',
    'Tank Condition & Securement',
    'Date of LP System Inspection',
  ],
  'Water Systems': [
    'Freshwater Tank Sanitized',
    'Water Pump Pressure Test (40-60 PSI)',
    'Hot Water Heater Anode Rod Condition',
    'Faucets (No drips, proper flow)',
    'Toilet Operation & Seal',
    'Shower Pan (No cracks, proper drain)',
    'City Water Connection (No leaks under pressure)',
    'Gray Tank Valve Operation',
    'Black Tank Valve Operation',
    'Winterization Status (If applicable)',
  ],
  'Electrical Systems': [
    '30/50 Amp Shore Power Connection Condition',
    'Transfer Switch Operation (Shore/Generator/Inverter)',
    'Inverter/Converter Output Voltage',
    'GFCI Outlets Functional (Kitchen, Bath, Exterior)',
    'House Battery Voltage Under Load',
    'Solar Panel Output (If equipped)',
    'Generator Start & Load Test',
    'All Interior Lights Operational',
    'Exterior Lighting (Porch, Compartments)',
  ],
  'Safety & Emergency': [
    'Smoke Detector(s) Operational (Test)',
    'CO Detector Operational (Test)',
    'LP Gas Detector Operational (Test)',
    'Fire Extinguisher Charged & Accessible',
    'Emergency Exit Window(s) Operational',
    'Entry Door Lock & Deadbolt',
    'Entry Step Mechanism (Electric/Manual)',
  ],
};

// Classic / vintage car authenticity checklist
export const CLASSIC_AUTHENTICITY_CHECKLIST = {
  'Numbers Matching Verification': [
    'VIN Tag Present & Legible',
    'VIN Matches Title',
    'Engine Stamp/Casting Number Matches',
    'Transmission Stamp/Casting Number Matches',
    'Rear Axle Code/Tag (If applicable)',
    'Body/Cowl Tag Data Matches Records',
    'Trim/Paint Codes Match Factory Spec',
    'Date Codes Sequential (Body, Engine, Trans)',
  ],
  'Originality Assessment': [
    'Paint: Original, Repaint, or Bare Metal Restore',
    'Interior: Original, Correct Reproduction, or Custom',
    'Engine: Original, Correct Replacement, or Swap',
    'Transmission: Original or Replacement',
    'Carburetor/Fuel System: Correct for Year/Model',
    'Exhaust Manifolds: Original or Headers',
    'Suspension: Stock, Upgraded, or Lowered/Lifted',
    'Wheels/Hubcaps: Period-Correct or Aftermarket',
    'Radio/Electronics: Original, Period-Correct, or Modern',
  ],
  'Rust & Body Integrity': [
    'Rocker Panels (Probe for hidden rust)',
    'Quarter Panels (Check for filler/patches)',
    'Trunk Floor Condition',
    'Door Bottoms & Drain Holes',
    'Windshield & Rear Window Channels',
    'Fender Wells (Inner lip rust)',
    'Cowl Area (Water drain paths)',
    'Frame/Subframe Condition (Surface vs structural)',
  ],
  'Provenance & Documentation': [
    'Chain of Ownership',
    'Original Title or MSO',
    'Factory Build Sheet / Window Sticker',
    'Historical Registration Records',
    'Restoration Receipts & Documentation',
    'Concours Judging Sheets (If applicable)',
    'Published History or Magazine Features',
    'Appraisal Date & Value',
  ],
};
